service: serverless-job-posting

org: programmingproject

provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  timeout: 60
  
  
resources:
  Resources:
    ApiGatewayAuthorizer:
      DependsOn:
        - ApiGatewayRestApi
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: cognito-authorizer
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs: 
          - arn:aws:cognito-idp:us-east-1:260383621052:userpool/us-east-1_YlxNmu1j2
        


functions:
  booking:
    handler: main.jobs
    events:
      - http:
          path: /jobs
          method: get
          authorizer:
             type: COGNITO_USER_POOLS
             authorizerId:
               Ref: ApiGatewayAuthorizer
  create-job:
    handler: main.create_job
    events:
      - http:
          path: /create_job
          method: post
          authorizer:
             type: COGNITO_USER_POOLS
             authorizerId:
               Ref: ApiGatewayAuthorizer
  resume:
    handler: main.resume
    events:
      - http:
          path: /resume
          method: post
          authorizer:
             type: COGNITO_USER_POOLS
             authorizerId:
               Ref: ApiGatewayAuthorizer
  get-filtered-jobs:
    handler: main.get_filtered_jobs
    events:
      - http:
          path: /getFilteredJobs/{degree}
          method: get
          request:
            parameters:
              paths:
                degree: true
          authorizer:
             type: COGNITO_USER_POOLS
             authorizerId:
               Ref: ApiGatewayAuthorizer
  get-filtered-job-id:
    handler: main.get_filter_job_id
    events:
      - http:
          path: /getFilterJobs/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
          authorizer:
             type: COGNITO_USER_POOLS
             authorizerId:
               Ref: ApiGatewayAuthorizer
  edit-job-posting:
    handler: main.edit_job_posting
    events:
      - http:
          path: /editJob
          method: post
          authorizer:
             type: COGNITO_USER_POOLS
             authorizerId:
               Ref: ApiGatewayAuthorizer
  delete-job-posting:
    handler: main.delete_job_posting
    events:
      - http:
          path: /deleteJob
          method: delete
          authorizer:
             type: COGNITO_USER_POOLS
             authorizerId:
               Ref: ApiGatewayAuthorizer
  getJobsForEmployee:
    handler: main.getJobsForEmployee
    events:
      - http:
          path: /getEmployeeJobs
          method: get
          authorizer:
             type: COGNITO_USER_POOLS
             authorizerId:
               Ref: ApiGatewayAuthorizer
  apply-job:
    handler: main.apply_job
    events:
      - http:
          path: /apply_job
          method: post
          authorizer:
             type: COGNITO_USER_POOLS
             authorizerId:
               Ref: ApiGatewayAuthorizer
  get-applicants-for-a-job:
    handler: main.get_applicants_for_job
    events:
      - http:
          path: /getApplicantJobs/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
          authorizer:
             type: COGNITO_USER_POOLS
             authorizerId:
               Ref: ApiGatewayAuthorizer
                       
               
    
